[package]
name = "namenode"
version = "0.1.0"
authors = ["Daniel Rammer <hamersaw@bushpath.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
env_logger = "0.6"
hdfs-comm = { path = "../../../utilities-rs/hdfs-comm" }
hdfs-protos = { path = "../../../utilities-rs/hdfs-protos" }
log = "0.4"
prost = "0.5"
rand = "0.6"
