[package]
name = "cli"
version = "0.1.0"
authors = ["Daniel Rammer <hamersaw@bushpath.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
hdfs-comm = { path = "../../../utilities-rs/hdfs-comm" }
prost = "0.5"
shared = { path = "../shared" }
